language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
    - php: 7.0

before_script:
  - "mkdir -p ~/.composer"
  - openssl aes-256-cbc -K $encrypted_00d4fc3a7399_key -iv $encrypted_00d4fc3a7399_iv -in .travis.composer.config.json.enc -out ~/.composer/config.json -d
  - composer self-update
  - composer install

script:
  - vendor/bin/phpunit --coverage-text

after_success:
  - composer require satooshi/php-coveralls
  - vendor/bin/coveralls
